### ISSUE TITLE
 Can't run with dlopen

### ISSUE THREAD

**Issue by nguyentuan3691** [Qusic/proxychains-ios#1]
Hello
When type command on ssh with syntax: dlopen(/usr/lib/proxychains_loader.dylib) then show error message "syntax error near unexpected token `/usr/lib/proxychains_loader.dylib'"

How to fix this error?
Thanks

**Comment by Qusic** [comment]
I meant this [dlopen](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/dlopen.3.html)
the main use case is to use it with cydia substrate, instead of only from command line with the command `proxychains`
